### ISSUE TITLE
Postcss-cli is blocking this action from working

### ISSUE THREAD

**Issue by ryanjbartley** [chabad360/hugo-gh-pages#13]
I have made no substantive changes to either site (only markdown) and now suddenly both sites fail to build with a warning about PostCSS

Runtime Environment (ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'postcss'
Require stack:
- /usr/lib/node_modules/postcss-cli/index.js
- /usr/lib/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/postcss-cli/index.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/postcss-cli/index.js',
    '/usr/lib/node_modules/postcss-cli/bin/postcss'
  ]
}
PostCSS:

**Comment by sharksforarms** [comment]
Same here, was working ~4 hours ago

Edit: Looks like the [underlying docker image](https://hub.docker.com/r/chabad360/hugo) was updated ~3 hours ago

**Comment by chabad360** [comment]
Thank you both for reporting on this, I personally haven't been blogging enough that I would notice this issue (isn't open source wonderful?).

> Edit: Looks like the [underlying docker image](https://hub.docker.com/r/chabad360/hugo) was updated ~3 hours ago

It's scheduled to update once a week.

Regardless, it seems that for some reason `postcss-cli` is missing its `postcss` dependency...

@sharksforarms I'll merge your PR soon (just wanna ask a few questions first) which should solve this issue.

**Comment by chabad360** [comment]
Just merged! Leaving this issue open till either of you can confirm it's working (should be about 15 min).

**Comment by ryanjbartley** [comment]
It appears to be resolved for me. Publishing worked without further complaint. Thanks, everybody. And yes, this is why I insist on open source for everything I can. 💜
